version: "3.7"
services:
  bot:
    build: app
    container_name: tg_bot
    environment:
      - BOT_TOKEN=6809020745:AAFxAlu-QZR9WkGGwF1rZl1fiZH8yREVvpI
    networks:
      app-network:
        aliases:
          - bot

  api:
    build: app/api
    container_name: fastapi_app1
    ports:
      - 9999:8000
    networks:
      app-network:
        aliases:
          - api

networks:
  app-network:
    driver: bridge
    attachable: true